module.exports = [
    {
      "city": "Sydney", 
      "lat": "-33.8650", 
      "lng": "151.2094", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "admin", 
      "population": "5312163", 
      "population_proper": "4840600"
    }, 
    {
      "city": "Melbourne", 
      "lat": "-37.8136", 
      "lng": "144.9631", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "admin", 
      "population": "5078193", 
      "population_proper": "4529500"
    }, 
    {
      "city": "Brisbane", 
      "lat": "-27.4678", 
      "lng": "153.0281", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "admin", 
      "population": "2514184", 
      "population_proper": "2360241"
    }, 
    {
      "city": "Perth", 
      "lat": "-31.9522", 
      "lng": "115.8589", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "admin", 
      "population": "2059484", 
      "population_proper": "2039200"
    }, 
    {
      "city": "Adelaide", 
      "lat": "-34.9289", 
      "lng": "138.6011", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "admin", 
      "population": "1345777", 
      "population_proper": "1295714"
    }, 
    {
      "city": "Gold Coast", 
      "lat": "-28.0167", 
      "lng": "153.4000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "679127", 
      "population_proper": "638090"
    }, 
    {
      "city": "Cranbourne", 
      "lat": "-38.0996", 
      "lng": "145.2834", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "460491", 
      "population_proper": "39419"
    }, 
    {
      "city": "Canberra", 
      "lat": "-35.2931", 
      "lng": "149.1269", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Australian Capital Territory", 
      "capital": "primary", 
      "population": "426704", 
      "population_proper": "381488"
    }, 
    {
      "city": "Newcastle", 
      "lat": "-32.9167", 
      "lng": "151.7500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "322278", 
      "population_proper": "152984"
    }, 
    {
      "city": "Wollongong", 
      "lat": "-34.4331", 
      "lng": "150.8831", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "302739", 
      "population_proper": "289236"
    }, 
    {
      "city": "Geelong", 
      "lat": "-38.1500", 
      "lng": "144.3500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "263280", 
      "population_proper": "191440"
    }, 
    {
      "city": "Hobart", 
      "lat": "-42.8806", 
      "lng": "147.3250", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Tasmania", 
      "capital": "admin", 
      "population": "240342", 
      "population_proper": "222356"
    }, 
    {
      "city": "Townsville", 
      "lat": "-19.2564", 
      "lng": "146.8183", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "180820", 
      "population_proper": "178649"
    }, 
    {
      "city": "Ipswich", 
      "lat": "-27.6167", 
      "lng": "152.7667", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "163000", 
      "population_proper": "163000"
    }, 
    {
      "city": "Cairns", 
      "lat": "-16.9303", 
      "lng": "145.7703", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "152729", 
      "population_proper": "146778"
    }, 
    {
      "city": "Toowoomba", 
      "lat": "-27.5667", 
      "lng": "151.9500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "136861", 
      "population_proper": "135631"
    }, 
    {
      "city": "Darwin", 
      "lat": "-12.4381", 
      "lng": "130.8411", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Northern Territory", 
      "capital": "admin", 
      "population": "136828", 
      "population_proper": "136828"
    }, 
    {
      "city": "Ballarat", 
      "lat": "-37.5500", 
      "lng": "143.8500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "105471", 
      "population_proper": "98543"
    }, 
    {
      "city": "Bendigo", 
      "lat": "-36.7500", 
      "lng": "144.2667", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "99122", 
      "population_proper": "95587"
    }, 
    {
      "city": "Launceston", 
      "lat": "-41.4419", 
      "lng": "147.1450", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Tasmania", 
      "capital": "", 
      "population": "87328", 
      "population_proper": "87328"
    }, 
    {
      "city": "Mackay", 
      "lat": "-21.1411", 
      "lng": "149.1861", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "80148", 
      "population_proper": "3659"
    }, 
    {
      "city": "Rockhampton", 
      "lat": "-23.3750", 
      "lng": "150.5117", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "78592", 
      "population_proper": "78592"
    }, 
    {
      "city": "Maitland", 
      "lat": "-32.7167", 
      "lng": "151.5500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "78015", 
      "population_proper": "1885"
    }, 
    {
      "city": "Bunbury", 
      "lat": "-33.3333", 
      "lng": "115.6333", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "74363", 
      "population_proper": "71090"
    }, 
    {
      "city": "Coffs Harbour", 
      "lat": "-30.3022", 
      "lng": "153.1189", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "71822", 
      "population_proper": "25752"
    }, 
    {
      "city": "Bundaberg", 
      "lat": "-24.8500", 
      "lng": "152.3500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "70921", 
      "population_proper": "70540"
    }, 
    {
      "city": "Wagga Wagga", 
      "lat": "-35.1189", 
      "lng": "147.3689", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "56442", 
      "population_proper": "54411"
    }, 
    {
      "city": "Hervey Bay", 
      "lat": "-25.2853", 
      "lng": "152.8728", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "54674", 
      "population_proper": "54674"
    }, 
    {
      "city": "Shepparton", 
      "lat": "-36.3833", 
      "lng": "145.4000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "51631", 
      "population_proper": "31197"
    }, 
    {
      "city": "Albury", 
      "lat": "-36.0806", 
      "lng": "146.9158", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "47974", 
      "population_proper": "4804"
    }, 
    {
      "city": "Port Macquarie", 
      "lat": "-31.4333", 
      "lng": "152.9000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "47973", 
      "population_proper": "44830"
    }, 
    {
      "city": "Pakenham", 
      "lat": "-38.0712", 
      "lng": "145.4878", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "46421", 
      "population_proper": "46421"
    }, 
    {
      "city": "Tamworth", 
      "lat": "-31.0833", 
      "lng": "150.9167", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "42872", 
      "population_proper": "180"
    }, 
    {
      "city": "Caloundra", 
      "lat": "-26.7986", 
      "lng": "153.1289", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "41293", 
      "population_proper": "41293"
    }, 
    {
      "city": "Orange", 
      "lat": "-33.2833", 
      "lng": "149.1000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "40493", 
      "population_proper": "38097"
    }, 
    {
      "city": "Dubbo", 
      "lat": "-32.2569", 
      "lng": "148.6011", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "38392", 
      "population_proper": "38392"
    }, 
    {
      "city": "Geraldton", 
      "lat": "-28.7744", 
      "lng": "114.6089", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "37648", 
      "population_proper": "37648"
    }, 
    {
      "city": "Nowra", 
      "lat": "-34.8833", 
      "lng": "150.6000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "37420", 
      "population_proper": "9193"
    }, 
    {
      "city": "Bathurst", 
      "lat": "-33.4200", 
      "lng": "149.5778", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "36801", 
      "population_proper": "35020"
    }, 
    {
      "city": "Queanbeyan", 
      "lat": "-35.3533", 
      "lng": "149.2342", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "36348", 
      "population_proper": "6237"
    }, 
    {
      "city": "Frankston", 
      "lat": "-38.1580", 
      "lng": "145.1350", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "36097", 
      "population_proper": "36097"
    }, 
    {
      "city": "Sunbury", 
      "lat": "-37.5811", 
      "lng": "144.7139", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "36084", 
      "population_proper": "36084"
    }, 
    {
      "city": "Warrnambool", 
      "lat": "-38.3833", 
      "lng": "142.4833", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "35214", 
      "population_proper": "29661"
    }, 
    {
      "city": "Wodonga", 
      "lat": "-36.1214", 
      "lng": "146.8881", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "35130", 
      "population_proper": "18948"
    }, 
    {
      "city": "Albany", 
      "lat": "-35.0228", 
      "lng": "117.8814", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "34205", 
      "population_proper": "29373"
    }, 
    {
      "city": "Gladstone", 
      "lat": "-23.8489", 
      "lng": "151.2625", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "33418", 
      "population_proper": "33418"
    }, 
    {
      "city": "Mildura", 
      "lat": "-34.1889", 
      "lng": "142.1583", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "32738", 
      "population_proper": "32738"
    }, 
    {
      "city": "Southport", 
      "lat": "-27.9667", 
      "lng": "153.4000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "31908", 
      "population_proper": "31908"
    }, 
    {
      "city": "Alice Springs", 
      "lat": "-23.7000", 
      "lng": "133.8667", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Northern Territory", 
      "capital": "", 
      "population": "31120", 
      "population_proper": "31120"
    }, 
    {
      "city": "Dandenong", 
      "lat": "-37.9810", 
      "lng": "145.2150", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "29906", 
      "population_proper": "29906"
    }, 
    {
      "city": "Kalgoorlie", 
      "lat": "-30.7489", 
      "lng": "121.4658", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "29849", 
      "population_proper": "29849"
    }, 
    {
      "city": "Mount Gambier", 
      "lat": "-37.8294", 
      "lng": "140.7828", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "", 
      "population": "29639", 
      "population_proper": "25512"
    }, 
    {
      "city": "Lismore", 
      "lat": "-28.8167", 
      "lng": "153.2833", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "28720", 
      "population_proper": "3579"
    }, 
    {
      "city": "Maryborough", 
      "lat": "-25.5375", 
      "lng": "152.7019", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "27282", 
      "population_proper": "15406"
    }, 
    {
      "city": "Quakers Hill", 
      "lat": "-33.7344", 
      "lng": "150.8789", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "27080", 
      "population_proper": "27080"
    }, 
    {
      "city": "Gawler", 
      "lat": "-34.5981", 
      "lng": "138.7450", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "", 
      "population": "26472", 
      "population_proper": "942"
    }, 
    {
      "city": "Caboolture", 
      "lat": "-27.0667", 
      "lng": "152.9670", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "26433", 
      "population_proper": "26433"
    }, 
    {
      "city": "Ballina", 
      "lat": "-28.8333", 
      "lng": "153.5333", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "26381", 
      "population_proper": "8655"
    }, 
    {
      "city": "Taree", 
      "lat": "-31.9000", 
      "lng": "152.4500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "26381", 
      "population_proper": "16197"
    }, 
    {
      "city": "Traralgon", 
      "lat": "-38.1958", 
      "lng": "146.5403", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "25485", 
      "population_proper": "24933"
    }, 
    {
      "city": "Busselton", 
      "lat": "-33.6478", 
      "lng": "115.3458", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "25329", 
      "population_proper": "25329"
    }, 
    {
      "city": "Armidale", 
      "lat": "-30.5000", 
      "lng": "151.6500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "24504", 
      "population_proper": "24504"
    }, 
    {
      "city": "Goulburn", 
      "lat": "-34.7547", 
      "lng": "149.6186", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "23835", 
      "population_proper": "22419"
    }, 
    {
      "city": "Devonport", 
      "lat": "-41.1806", 
      "lng": "146.3464", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Tasmania", 
      "capital": "", 
      "population": "23046", 
      "population_proper": "23046"
    }, 
    {
      "city": "Bacchus Marsh", 
      "lat": "-37.6750", 
      "lng": "144.4389", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "22223", 
      "population_proper": "6394"
    }, 
    {
      "city": "Whyalla", 
      "lat": "-33.0333", 
      "lng": "137.5667", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "", 
      "population": "21742", 
      "population_proper": "21742"
    }, 
    {
      "city": "Cessnock", 
      "lat": "-32.8342", 
      "lng": "151.3555", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "21725", 
      "population_proper": "15177"
    }, 
    {
      "city": "Gympie", 
      "lat": "-26.1900", 
      "lng": "152.6655", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "21599", 
      "population_proper": "10803"
    }, 
    {
      "city": "Griffith", 
      "lat": "-34.2900", 
      "lng": "146.0400", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "20251", 
      "population_proper": "18196"
    }, 
    {
      "city": "Kwinana", 
      "lat": "-32.2394", 
      "lng": "115.7702", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "20086", 
      "population_proper": "17549"
    }, 
    {
      "city": "Burnie", 
      "lat": "-41.0636", 
      "lng": "145.8753", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Tasmania", 
      "capital": "", 
      "population": "19385", 
      "population_proper": "19385"
    }, 
    {
      "city": "Wangaratta", 
      "lat": "-36.3583", 
      "lng": "146.3125", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "19318", 
      "population_proper": "17377"
    }, 
    {
      "city": "Grafton", 
      "lat": "-29.6833", 
      "lng": "152.9333", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "19078", 
      "population_proper": "10408"
    }, 
    {
      "city": "Yeppoon", 
      "lat": "-23.1333", 
      "lng": "150.7333", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "19003", 
      "population_proper": "6334"
    }, 
    {
      "city": "Murray Bridge", 
      "lat": "-35.1170", 
      "lng": "139.2670", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "", 
      "population": "18779", 
      "population_proper": "14560"
    }, 
    {
      "city": "Mount Isa", 
      "lat": "-20.7333", 
      "lng": "139.5000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "18588", 
      "population_proper": "118"
    }, 
    {
      "city": "Narangba", 
      "lat": "-27.2015", 
      "lng": "152.9655", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "18573", 
      "population_proper": "18573"
    }, 
    {
      "city": "Mount Eliza", 
      "lat": "-38.1890", 
      "lng": "145.0920", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "17888", 
      "population_proper": "17888"
    }, 
    {
      "city": "Broken Hill", 
      "lat": "-31.9567", 
      "lng": "141.4678", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "17734", 
      "population_proper": "17734"
    }, 
    {
      "city": "Nerang", 
      "lat": "-27.9956", 
      "lng": "153.3220", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Queensland", 
      "capital": "", 
      "population": "16864", 
      "population_proper": "16864"
    }, 
    {
      "city": "Karratha", 
      "lat": "-20.7364", 
      "lng": "116.8464", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Western Australia", 
      "capital": "", 
      "population": "16708", 
      "population_proper": "16708"
    }, 
    {
      "city": "Mount Barker", 
      "lat": "-35.0667", 
      "lng": "138.8500", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "South Australia", 
      "capital": "", 
      "population": "16629", 
      "population_proper": "13842"
    }, 
    {
      "city": "Horsham", 
      "lat": "-36.7167", 
      "lng": "142.2000", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "16514", 
      "population_proper": "14543"
    }, 
    {
      "city": "Lara", 
      "lat": "-38.0167", 
      "lng": "144.4167", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "Victoria", 
      "capital": "", 
      "population": "16355", 
      "population_proper": "16355"
    }, 
    {
      "city": "Singleton", 
      "lat": "-32.5667", 
      "lng": "151.1697", 
      "country": "Australia", 
      "iso2": "AU", 
      "admin_name": "New South Wales", 
      "capital": "", 
      "population": "16346", 
      "population_proper": "5000"
    },
  ];